_BASE_: ./configs/base.yaml

CONFIG:
    DATA_NAME: TINY-IMAGENET
    MODEL_NAME: RESNET
    DEPTH: 50

    CONV_BIAS: False

    DROPOUT_TYPE: BASIC
    DROPOUT_RATIO: 0.3

    RECONSTRUCT: False
    RECONSTRUCT_MSE_LOSS: False
    RECONSTRUCT_CE_LOSS: False
