SOLVER:
    LR: 0.25
    WEIGHT_DECAY: 0.0001
    NUM_EPOCHS: 300
    BATCH_SIZE: 64
    OPTIMIZER: SGD
    LR_DECAY_MILESTONE: [30, 60, 90, 120, 150, 180, 210, 240, 270]
    DECAY_FACTOR: 0.1

DATASET:
    CIFAR10:
        MEAN: [0.4913725490196078, 0.4823529411764706, 0.4466666666666667]
        STD: [0.24705882352941178, 0.24352941176470588, 0.2615686274509804]
        IMG_SIZE: 32
        NUM_CLASSES: 10

    CIFAR100:
        MEAN: [0.5070588235294118, 0.48666666666666664, 0.4407843137254902]
        STD: [0.26745098039215687, 0.2564705882352941, 0.27607843137254906]
        IMG_SIZE: 32
        NUM_CLASSES: 100

    SVHN:
        MEAN: [0.4309803921568628, 0.4301960784313726, 0.4462745098039216]
        STD: [0.19647058823529412, 0.1984313725490196, 0.1996078431372549]
        IMG_SIZE: 32
        NUM_CLASSES: 10

    TINY-IMAGENET:
        MEAN: [0.485, 0.456, 0.406]
        STD: [0.229, 0.224, 0.225]
        IMG_SIZE: 64
        NUM_CLASSES: 200
