_BASE_: ./configs/base.yaml

CONFIG:
    DATA_NAME: CIFAR100
    MODEL_NAME: RESNET
    DEPTH: 18

    CONV_BIAS: False

    DROPOUT_TYPE: NONE
    DROPOUT_RATIO: 0

    RECONSTRUCT: False
    RECONSTRUCT_MSE_LOSS: False
    RECONSTRUCT_CE_LOSS: False
